language: php

# php compatibility
php:
  - 7.0
  - 7.1
  - 7.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# sudo:false # remove this block

before_script:
  - |
    if [[ $TRAVIS_PHP_VERSION != '7.1' ]]; then
        phpenv config-rm xdebug.ini
    fi
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - mkdir -p build/tests/
  - vendor/bin/phpcs -sp src/ scripts/ tests/
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/tests/coverage.xml
  - vendor/bin/phpstan analyse --level max scripts/ src/ tests/

after_script:
  # upload to scrutinizer
  - |
    if [[ $TRAVIS_PHP_VERSION == '7.1' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/tests/coverage.xml
    fi

notifications:
  email: false
