language: php

# php compatibility
php:
  - 7.4

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - mkdir -p build/tests/
  - vendor/bin/phpcs -sp src/ scripts/ tests/
  - vendor/bin/phpunit --testdox --coverage-clover=build/tests/coverage.xml
  - vendor/bin/phpstan analyse --level max scripts/ src/ tests/

after_script:
  # upload to scrutinizer
  - |
    if [[ $TRAVIS_PHP_VERSION == '7.4' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/tests/coverage.xml
    fi

notifications:
  email: false
